# -----------------------------------------
# ğŸ” Kubernetes Secret for MongoDB URI
# -----------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: sustainat
type: Opaque
stringData:
  uri: mongodb+srv://sustainatltd:sustain123@sustainat-cluster.cb1qi.mongodb.net/sustainatdb

